// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnuO6CU_8Nh7jr7S9vY1aAEqdzIrtOblU',
    appId: '1:411093758435:web:35a70c05accb08eca3f0d6',
    messagingSenderId: '411093758435',
    projectId: 'pim-core-ddb2e',
    authDomain: 'pim-core-ddb2e.firebaseapp.com',
    storageBucket: 'pim-core-ddb2e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU_j7fMT-MpSfFenLzpyXATNwal-iBlRY',
    appId: '1:411093758435:android:e8b88d2705ebd44fa3f0d6',
    messagingSenderId: '411093758435',
    projectId: 'pim-core-ddb2e',
    storageBucket: 'pim-core-ddb2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARo20ZZ3Bs0AGKeTdC3E2w3nCztCWjkew',
    appId: '1:411093758435:ios:1130d7ca5be27783a3f0d6',
    messagingSenderId: '411093758435',
    projectId: 'pim-core-ddb2e',
    storageBucket: 'pim-core-ddb2e.firebasestorage.app',
    iosBundleId: 'com.example.stripe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARo20ZZ3Bs0AGKeTdC3E2w3nCztCWjkew',
    appId: '1:411093758435:ios:1130d7ca5be27783a3f0d6',
    messagingSenderId: '411093758435',
    projectId: 'pim-core-ddb2e',
    storageBucket: 'pim-core-ddb2e.firebasestorage.app',
    iosBundleId: 'com.example.stripe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnuO6CU_8Nh7jr7S9vY1aAEqdzIrtOblU',
    appId: '1:411093758435:web:2833a0f9e9a4b606a3f0d6',
    messagingSenderId: '411093758435',
    projectId: 'pim-core-ddb2e',
    authDomain: 'pim-core-ddb2e.firebaseapp.com',
    storageBucket: 'pim-core-ddb2e.firebasestorage.app',
  );
}
